name = "suipassport"
main = "src/lib/worker.ts"
compatibility_date = "2024-01-01"

[[d1_databases]]
binding = "DB"
database_name = "suipassport-mainnet"
database_id = "4ebcfcef-8cb4-407e-b547-dcdba2996d70"