name = "suipassport"
main = "src/lib/worker.ts"
compatibility_date = "2024-01-01"

[[d1_databases]]
binding = "DB"
database_name = "suipassport-mainnet"
database_id = "c542b152-b200-4c73-b2e1-d88c355af676"